"""add_country_code

Revision ID: 6bec72e67164
Revises: 692648041e13
Create Date: 2023-03-29 16:52:04.752446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6bec72e67164"
down_revision = "692648041e13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("country_code", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "country_code")
    # ### end Alembic commands ###
